meta_product_name: "Flavour"
meta_title: "Flavour - Add some Flavour to your community"
meta_description: "Experince your community and your city through meals"
meta_image: "https://res.cloudinary.com/duqna6ouc/image/upload/c_fill,h_3624,w_2904/v1544977503/priscilla-du-preez-697322-unsplash.jpg" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
